POST  http://localhost:4000/auth/register
Content-Type: application/json

{
    "UNAME":"Edimund",
    "EMAIL":"lintonmw@ueab.ac.ke",
    "UPASSWORD":"Lint@123",
    "Rolename":"GOVERNMENT"
   
}


####

POST http://localhost:4000/auth/login 
Content-Type: application/json

{
    "EMAIL":"lintonli162@gmail.com",
    "UPASSWORD":"Lint@123"
}

####

GET  http://localhost:4000/auth

#############
DELETE http://localhost:4000/auth/1

#####
PUT  http://localhost:4000/auth/approve/6224d99d-975f-44c7-af60-ccc0bc2fd6a5

#########
PATCH  http://localhost:4000/auth/JOHN@GMAIL.COM
Content-Type: application/json

{
    "UPASSWORD":"John@123"
}

########
POST http://localhost:4000/views
Content-Type: application/json

{
    "BODY":"The government should stop killing us gen -z and listen to what the youth are saying",
    "USERID":"ea9b9b59-c98d-430f-bd18-a905c7e48ae9"
}

########
GET http://localhost:4000/views


#########
POST  http://localhost:4000/incidents
Content-Type: application/json

{
    "ILOCATION":"Nyeri",
    "MEDIA":"join.png",
    "BODY":"TWO PEOPLE WERE SHOT DURING PROTESTS",
    "TDATE":"2024-07-16",
    "USERID":"ea9b9b59-c98d-430f-bd18-a905c7e48ae9"
}

######
GET  http://localhost:4000/incidents

###############
POST http://localhost:4000/polls
Content-Type: application/json

{
    "TITLE":"OCCOPY MOH",
    "USERID":"6224d99d-975f-44c7-af60-ccc0bc2fd6a5",
    "OPTIONS":[
        {
            "PNAME":"YES"
        },
        {
            "PNAME":"NO"
        }
    ]
}

#########
GET  http://localhost:4000/polls

#########
POST http://localhost:4000/polls/vote
Content-Type: application/json

{
    "POLLID":"446aed17-97e2-4c75-bb73-78678783e5db",
    "OPTIONID":"9c91bc03-a0ac-4e5a-9ce6-f9c6aa2c5c5b",
    "USERID":"6224d99d-975f-44c7-af60-ccc0bc2fd6a5"
}