USE CONNECT360
CREATE TABLE Incidents(
    ID VARCHAR(255) NOT NULL,
    ILOCATION VARCHAR(255) NOT NULL,
    MEDIA VARCHAR(255) NOT NULL,
    BODY VARCHAR(255) NOT NULL,
    TDATE VARCHAR(255) NOT NULL,
    USERID VARCHAR(255) NOT NULL,
    FOREIGN KEY(USERID) REFERENCES Users(ID)
)