USE CONNECT360;
CREATE TABLE Users(
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    UNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    UPASSWORD VARCHAR(255) NOT NULL,
    USTATUS VARCHAR(255) NOT NULL,
    isEmailSent INT DEFAULT 0,
    isDeleted INT DEFAULT 0,
    Rolename VARCHAR(255) NOT NULL,
    FOREIGN KEY (Rolename) REFERENCES Roles(RNAME) 
)