USE CONNECT360
CREATE TABLE Votes(
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    POLLID VARCHAR(255) NOT NULL,
    OPTIONID VARCHAR(255) NOT NULL,
    USERID VARCHAR(255) NOT NULL,
    FOREIGN KEY(POLLID) REFERENCES Polls(ID),
    FOREIGN KEY(OPTIONID) REFERENCES PollOptions(ID),
    FOREIGN KEY(USERID) REFERENCES Users(ID)
)

DROP TABLE Votes;