USE CONNECT360
GO
CREATE OR ALTER PROCEDURE addIncident(@ID VARCHAR(255), @ILOCATION VARCHAR(255), @MEDIA VARCHAR(255), @BODY VARCHAR(255), @TDATE VARCHAR(255), @USERID VARCHAR(255))
AS
BEGIN
INSERT INTO Incidents(ID, ILOCATION,MEDIA,BODY,TDATE,USERID)
VALUES(@ID, @ILOCATION, @MEDIA, @BODY, @TDATE, @USERID)
END