USE CONNECT360;
GO
CREATE OR ALTER PROCEDURE addUser(
    @ID VARCHAR(255),
    @NAME VARCHAR(255),
    @EMAIL VARCHAR(255),
    @PASSWORD VARCHAR(255),
    @ROLE VARCHAR(255),
    @STATUS VARCHAR(255)
)
AS 
BEGIN
IF @ROLE ='GOVERNMENT'
SET @STATUS= 'PENDING'
ELSE IF @ROLE ='CITIZEN'
SET @STATUS ='APPROVED'
INSERT INTO Users(ID,UNAME,EMAIL,UPASSWORD,USTATUS,Rolename)
VALUES(@ID, @NAME,@EMAIL,@PASSWORD,@STATUS,@ROLE)
END;



